# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_web.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PushButton_make_html = PushButton(Form)
        self.PushButton_make_html.setObjectName("PushButton_make_html")
        self.gridLayout_2.addWidget(self.PushButton_make_html, 4, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.PushButton_choose_file = PushButton(Form)
        self.PushButton_choose_file.setObjectName("PushButton_choose_file")
        self.gridLayout.addWidget(self.PushButton_choose_file, 0, 2, 1, 1)
        self.LineEdit_url_or_html = LineEdit(Form)
        self.LineEdit_url_or_html.setObjectName("LineEdit_url_or_html")
        self.gridLayout.addWidget(self.LineEdit_url_or_html, 0, 1, 1, 1)
        self.ComboBox_where = ComboBox(Form)
        self.ComboBox_where.setObjectName("ComboBox_where")
        self.gridLayout.addWidget(self.ComboBox_where, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(779, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.PushButton_get_text = PushButton(Form)
        self.PushButton_get_text.setObjectName("PushButton_get_text")
        self.gridLayout_2.addWidget(self.PushButton_get_text, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 509, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 5, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.PushButton_make_html.setText(_translate("Form", "生成网页"))
        self.PushButton_choose_file.setText(_translate("Form", "浏览"))
        self.PushButton_get_text.setText(_translate("Form", "提取文本"))
from qfluentwidgets import ComboBox, LineEdit, PushButton
