# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_ip_check.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormIpCheck(object):
    def setupUi(self, FormIpCheck):
        FormIpCheck.setObjectName("FormIpCheck")
        FormIpCheck.resize(800, 600)
        self.gridLayout_4 = QtWidgets.QGridLayout(FormIpCheck)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.indeterminateProgressBar_run = IndeterminateProgressBar(FormIpCheck)
        self.indeterminateProgressBar_run.setObjectName("indeterminateProgressBar_run")
        self.gridLayout_3.addWidget(self.indeterminateProgressBar_run, 0, 1, 1, 1)
        self.checkBox_IPv6 = CheckBox(FormIpCheck)
        self.checkBox_IPv6.setEnabled(False)
        self.checkBox_IPv6.setObjectName("checkBox_IPv6")
        self.gridLayout_3.addWidget(self.checkBox_IPv6, 0, 2, 1, 1)
        self.checkBox_s = CheckBox(FormIpCheck)
        self.checkBox_s.setEnabled(False)
        self.checkBox_s.setObjectName("checkBox_s")
        self.gridLayout_3.addWidget(self.checkBox_s, 0, 3, 1, 1)
        self.primaryPushButton_run = PrimaryPushButton(FormIpCheck)
        self.primaryPushButton_run.setProperty("hasIcon", True)
        self.primaryPushButton_run.setObjectName("primaryPushButton_run")
        self.gridLayout_3.addWidget(self.primaryPushButton_run, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.HyperlinkLabel = HyperlinkLabel(FormIpCheck)
        self.HyperlinkLabel.setUrl(QtCore.QUrl("https://github.com/Ponderfly/GoogleTranslateIpCheck"))
        self.HyperlinkLabel.setObjectName("HyperlinkLabel")
        self.gridLayout.addWidget(self.HyperlinkLabel, 0, 0, 1, 1)
        self.BodyLabel = BodyLabel(FormIpCheck)
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout.addWidget(self.BodyLabel, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.plainTextEdit_output = PlainTextEdit(FormIpCheck)
        self.plainTextEdit_output.setReadOnly(True)
        self.plainTextEdit_output.setObjectName("plainTextEdit_output")
        self.gridLayout_4.addWidget(self.plainTextEdit_output, 4, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.progressBar_download = ProgressBar(FormIpCheck)
        self.progressBar_download.setObjectName("progressBar_download")
        self.gridLayout_2.addWidget(self.progressBar_download, 0, 1, 1, 1)
        self.pushButton_download = PushButton(FormIpCheck)
        self.pushButton_download.setProperty("hasIcon", True)
        self.pushButton_download.setObjectName("pushButton_download")
        self.gridLayout_2.addWidget(self.pushButton_download, 0, 0, 1, 1)
        self.checkBox_moeyy = CheckBox(FormIpCheck)
        self.checkBox_moeyy.setChecked(True)
        self.checkBox_moeyy.setObjectName("checkBox_moeyy")
        self.gridLayout_2.addWidget(self.checkBox_moeyy, 0, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.TitleLabel = TitleLabel(FormIpCheck)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout_4.addWidget(self.TitleLabel, 0, 0, 1, 1)

        self.retranslateUi(FormIpCheck)
        QtCore.QMetaObject.connectSlotsByName(FormIpCheck)

    def retranslateUi(self, FormIpCheck):
        _translate = QtCore.QCoreApplication.translate
        FormIpCheck.setWindowTitle(_translate("FormIpCheck", "Form"))
        self.checkBox_IPv6.setText(_translate("FormIpCheck", "IPv6"))
        self.checkBox_s.setText(_translate("FormIpCheck", "扫描模式"))
        self.primaryPushButton_run.setText(_translate("FormIpCheck", "运行"))
        self.HyperlinkLabel.setText(_translate("FormIpCheck", "https://github.com/Ponderfly/GoogleTranslateIpCheck"))
        self.BodyLabel.setText(_translate("FormIpCheck", "MIT license"))
        self.pushButton_download.setText(_translate("FormIpCheck", "下载"))
        self.checkBox_moeyy.setText(_translate("FormIpCheck", "moeyy加速"))
        self.TitleLabel.setText(_translate("FormIpCheck", "GoogleTranslateIpCheck"))
from qfluentwidgets import BodyLabel, CheckBox, HyperlinkLabel, IndeterminateProgressBar, PlainTextEdit, PrimaryPushButton, ProgressBar, PushButton, TitleLabel
