# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormSettings(object):
    def setupUi(self, FormSettings):
        FormSettings.setObjectName("FormSettings")
        FormSettings.resize(800, 600)
        self.gridLayout_2 = QtWidgets.QGridLayout(FormSettings)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TitleLabel = TitleLabel(FormSettings)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout_2.addWidget(self.TitleLabel, 0, 0, 1, 1)
        self.SmoothScrollArea = SmoothScrollArea(FormSettings)
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 537))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ElevatedCardWidget = ElevatedCardWidget(self.scrollAreaWidgetContents)
        self.ElevatedCardWidget.setObjectName("ElevatedCardWidget")
        self.gridLayout_lang = QtWidgets.QGridLayout(self.ElevatedCardWidget)
        self.gridLayout_lang.setObjectName("gridLayout_lang")
        self.SubtitleLabel = SubtitleLabel(self.ElevatedCardWidget)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.gridLayout_lang.addWidget(self.SubtitleLabel, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.ElevatedCardWidget, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 449, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.SmoothScrollArea, 1, 0, 1, 1)

        self.retranslateUi(FormSettings)
        QtCore.QMetaObject.connectSlotsByName(FormSettings)

    def retranslateUi(self, FormSettings):
        _translate = QtCore.QCoreApplication.translate
        FormSettings.setWindowTitle(_translate("FormSettings", "Form"))
        self.TitleLabel.setText(_translate("FormSettings", "设置"))
        self.SubtitleLabel.setText(_translate("FormSettings", "语言"))
from qfluentwidgets import ElevatedCardWidget, SmoothScrollArea, SubtitleLabel, TitleLabel
