name: 打包谷歌生草机核心

on:
  workflow_dispatch:
    inputs:
      version_tuple:
        description: '版本元组'
        required: true
      version_str:
        description: '版本字符串'
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: 签出存储库
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: 安装依赖项
        run: |
          pip install -r src/core/requirements-core.txt

      - name: 构建可执行文件
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/core/gggm_core.py
          standalone: true
          #disable-plugins: options-nanny
          nofollow-import-to: Pillow,PIL,numpy
          output-file: gggm_core
          company-name: 谷歌生草机开发组
          product-name: 谷歌生草机
          file-version: ${{ github.event.inputs.version_tuple }}
          product-version: ${{ github.event.inputs.version_tuple }}
          file-description: 谷歌生草机
          copyright: "Copyright 谷歌生草机开发组. All right reserved."
          windows-icon-from-ico: img/icon.ico
          macos-app-icon: img/icon.ico
          linux-icon: img/icon.ico

      - name: 上传工件
        uses: actions/upload-artifact@v3
        with:
          name: GoogleGrassGrowingMachine-core-v${{ github.event.inputs.version_str }}-${{ runner.os }}
          path: |
            build/gggm_core.dist/*
