name: 运行谷歌生草机核心

on:
  workflow_dispatch:
    inputs:
      r:
        description: 要生草的文件路径
        required: true
      o:
        description: 输出的文件路径，不带后缀
        required: true
      u:
        description: 谷歌翻译（镜像）网站
        default: https://translate.google.com
      ts:
        description: 翻译次数
        default: 20
      to:
        description: 超时
        default: 5
      rt:
        description: 自动重试次数
        default: 5
      sn:
        description: 使用逐句翻译
        default: false
      l:
        description: 使用的语言，默认为ALL，联合国六大语言为UN6
        default: ALL
      m:
        description: 最大线程数量
        default: 100
      sp:
        description: 分隔符
        default: \n。？！：,.

jobs:
  translate:
    runs-on: windows-latest

    steps:
      - name: 签出存储库
        uses: actions/checkout@v3

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: 安装依赖项
        run: |
          pip install -r src/core/requirements-core.txt

      - name: 生草
        run: |
          python src/core/gggm_core.py -r ${{ github.event.inputs.r }} -o ${{ github.event.inputs.o }} -u ${{ github.event.inputs.u }} -ts ${{ github.event.inputs.ts }} -to ${{ github.event.inputs.to }} -rt ${{ github.event.inputs.rt }} ${{ (github.event.inputs.sn == 'true') && '-sn' || '' }} -l ${{ github.event.inputs.l }} -m ${{ github.event.inputs.m }} -sp ${{ github.event.inputs.sp }}

      - name: 上传工件
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.o }}
          path: |
            ${{ github.event.inputs.o }}.txt